server: 
  port: 7000
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads

spring:
  profiles: 
    active: dev
  application: 
    name: udap-minicontract
  datasource:
    url: jdbc:mysql://47.97.34.209:3306/contract?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name : com.mysql.jdbc.Driver
  jpa: 
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  jackson: 
    serialization: 
      fail-on-empty-beans: false

web3j:
  client-address: http://localhost:8545
  httpTimeoutSeconds: 600

mini-contract:
  ethereum-address:7d6fe5e2ad3f4b980f56727a9651f1b0efcfd856
  ethereum-privatekey: 79972a6328ab7fd6bc90cae4b72fa41e9ad6ee376f39c0ebd5c4926157f1e97f
